project:
  type: book
  output-dir: docs

book:
  title: "Sistemas de Información Geográfica en R"
  author: "Manuel Vargas"
  date: "2025-06-03"

  chapters:
    - index.qmd
    - text: "Programa del curso"
      href: programa-curso-sigenr-2025-i.pdf
    - part: "I Introducción a la programación de computadoras y a la ciencia de datos"
      chapters:
        - 01-introduccion-programacion-computadoras.qmd
        - 02-introduccion-ciencia-datos.qmd
    - part: "II El lenguaje de programación R"
      chapters:
        - 03-r.qmd
        - 04-tidyverse.qmd
        - 05-dplyr.qmd
    - part: "III Herramientas para investigación reproducible y desarrollo colaborativo"
      chapters:
        - 06-markdown.qmd
        - 07-git.qmd
        - 08-quarto.qmd
    - part: "IV Graficación estadística en R"
      chapters:
        - 09-ggplot2-plotly.qmd
    - part: "V El ecosistema espacial de R"
      chapters:
        - 10-introduccion-manejo-datos-geoespaciales.qmd
        - 11-operaciones-datos-atributos.qmd
        - 12-operaciones-datos-espaciales.qmd
bibliography: referencias.bib
csl: apa-6th-edition.csl

format:
  html:
    lang: es
    theme: cosmo
    toc-expand: 5
